# Generated by Django 6.0.7 on 2026-07-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=False)),
                ("description", models.CharField(max_length=200)),
                ("stack", models.CharField(max_length=100)),
                ("link", models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TechnicalStrength",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("technology", models.CharField(max_length=50)),
            ],
        ),
    ]
