# Generated by Django 6.0.7 on 2026-08-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
