# Generated by Django 6.0.7 on 2026-08-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_project_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="description_es",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="name_es",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
