# Generated by Django 6.0.7 on 2026-08-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_project_description_en_project_description_es_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="stack",
        ),
        migrations.AddField(
            model_name="project",
            name="stack",
            field=models.ManyToManyField(
                related_name="projects",
                related_query_name="project",
                to="portfolio.technicalstrength",
            ),
        ),
    ]
