# Generated by Django 6.0.7 on 2026-08-04 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_remove_project_stack_project_stack"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="project",
            name="name_es",
        ),
    ]
