# Generated by Django 6.0.7 on 2026-08-18 03:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_remove_project_name_en_remove_project_name_es"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="description_es",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="technicalstrength",
            name="technology",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField(auto_now_add=True)),
                ("content", models.TextField()),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portfolio.project",
                    ),
                ),
                (
                    "stack",
                    models.ManyToManyField(
                        related_name="logs",
                        related_query_name="log",
                        to="portfolio.technicalstrength",
                    ),
                ),
            ],
        ),
    ]
