# Generated by Django 6.0.7 on 2026-08-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_alter_project_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logentry",
            options={"get_latest_by": "-date", "ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="logentry",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
