# Generated by Django 6.0.7 on 2026-08-19 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_alter_logentry_options_alter_logentry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portfolio.project",
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="stack",
            field=models.ManyToManyField(
                blank=True,
                related_name="logs",
                related_query_name="log",
                to="portfolio.technicalstrength",
            ),
        ),
    ]
