# Generated by Django 6.0.7 on 2026-08-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_alter_logentry_project_alter_logentry_stack"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Markdown content for the project case study",
                null=True,
            ),
        ),
    ]
