# Generated by Django 6.0.7 on 2026-08-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_project_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
