# Generated by Django 6.0.7 on 2026-09-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_logentry_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="content_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="content_es",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="title_es",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
