# Generated by Django 6.0.7 on 2026-09-02 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_logentry_content_en_logentry_content_es_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logentry",
            options={
                "get_latest_by": "-date",
                "ordering": ["-date"],
                "verbose_name_plural": "Log entries",
            },
        ),
    ]
